name: Gerar EPGs Automaticamente

on:
  schedule:
    - cron: '0 3 * * *' # Roda diariamente às 00:00 (Horário de Brasília)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install requests bs4 playwright
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          playwright install chromium --with-deps

      - name: Executar Script Principal (Claro)
        run: python gerar_epg.py

      - name: Executar Script Secundário (Guia de TV)
        run: python gerar_epg_guiadetv.py

      - name: Limpar e Filtrar EPG do GitHub
        run: python limpar_epg_github.py

      - name: Commit e Push dos Arquivos Gerados
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add epg.xml epg_guiadetv.xml epg_limpo.xml
          git commit -m "Atualização automática dos EPGs" || exit 0
          git push
